export const POST_CART_ITEM = 'POST_CART_ITEM'
export const POST_CART_ITEM_SUCCESS = 'POST_CART_ITEM_SUCCESS'
export const POST_CART_ITEM_FAILED = 'POST_CART_ITEM_FAILED'
export const POST_CART_ITEM_RESET = 'POST_CART_ITEM_RESET'

export const GET_CARTS = 'GET_CARTS'
export const GET_CARTS_SUCCESS = 'GET_CARTS_SUCCESS'
export const GET_CARTS_FAILED = 'GET_CARTS_FAILED'
export const GET_CARTS_RESET = 'GET_CARTS_RESET'

export const REMOVE_CART = 'REMOVE_CART'
export const REMOVE_CART_SUCCESS = 'REMOVE_CART_SUCCESS'
export const REMOVE_CART_FAILED = 'REMOVE_CART_FAILED'
export const REMOVE_CART_RESET = 'REMOVE_CART_RESET'

export const CHANGE_AMOUNT = 'CHANGE_AMOUNT'

export const UPDATE_CART = 'UPDATE_CART'
export const UPDATE_CART_SUCCESS = 'UPDATE_CART_SUCCESS'
export const UPDATE_CART_FAILED = 'UPDATE_CART_FAILED'