export const GET_PRODUCTS_REQUEST = 'GET_PRODUCTS_REQUEST'
export const GET_PRODUCTS_SUCCESS = 'GET_PRODUCTS_SUCCESS'
export const GET_PRODUCTS_FAILED = 'GET_PRODUCTS_FAILED'

export const GET_SINGLE_ARTICULE = 'GET_SINGLE_ARTICULE'
export const GET_SINGLE_ARTICULE_SUCCESS = 'GET_SINGLE_ARTICULE_SUCCESS'
export const GET_SINGLE_ARTICULE_FAILED = 'GET_SINGLE_ARTICULE_FAILED'

export const GET_SINGLE_PRODUCT_ITEM = 'GET_SINGLE_PRODUCT_ITEM'
export const GET_SINGLE_PRODUCT_ITEM_SUCCESS = 'GET_SINGLE_PRODUCT_ITEM_SUCCESS'
export const GET_SINGLE_PRODUCT_ITEM_FAILED = 'GET_SINGLE_PRODUCT_ITEM_FAILED'

export const SELECTED_PRODUCT = 'SELECTED_PRODUCT'

export const GET_SINGLE_SALE = 'GET_SINGLE_SALE'
export const GET_SINGLE_SALE_SUCCESS = 'GET_SINGLE_SALE_SUCCESS'
export const GET_SINGLE_SALE_FAILED = 'GET_SINGLE_SALE_FAILED'

export const FILL_FILTERED_PRODUCTS = 'FILL_FILTERED_PRODUCTS'

export const FILTER_PRICE = 'FILTER_PRICE'
export const FILTER_COLOR = 'FILTER_COLOR'
export const FILTER_ADDITIONAL = 'FILTER_ADDITIONAL'
export const FILTER_RESET = 'FILTER_RESET'
