export const IS_SEARCHING_PRODUCTS = 'IS_SEARCHING_PRODUCTS'
export const RESET_SEARCH = 'RESET_SEARCH'

export const GET_SEARCH_PRODUCTS = 'GET_SEARCH_PRODUCTS'
export const GET_SEARCH_PRODUCTS_SUCCESS = 'GET_SEARCH_PRODUCTS_SUCCESS'
export const GET_SEARCH_PRODUCTS_FAILED = 'GET_SEARCH_PRODUCTS_FAILED'
export const GET_SEARCH_PRODUCTS_RESET = 'GET_SEARCH_PRODUCTS_RESET'