export const SET_ACTIVE_CATEGORY = 'SET_ACTIVE_CATEGORY'
export const CLEAR_CATEGORY = 'CLEAR_CATEGORY'

export const GET_MAINPAGE = 'GET_MAINPAGE'
export const GET_MAINPAGE_SUCCESS = 'GET_MAINPAGE_SUCCESS'
export const GET_MAINPAGE_FAILED = 'GET_MAINPAGE_FAILED'