export const ORDER_VALIDATION_FAILED = 'ORDER_VALIDATION_FAILED'
export const ORDER_VALIDATION_SUCCESS = 'ORDER_VALIDATION_SUCCESS'
export const ORDER_VALIDATION_RESET = 'ORDER_VALIDATION_RESET'

export const POST_ORDER = 'POST_ORDER'
export const POST_ORDER_SUCCESS = 'POST_ORDER_SUCCESS'
export const POST_ORDER_FAILED = 'POST_ORDER_FAILED'
export const POST_ORDER_RESET = 'POST_ORDER_RESET'

export const GET_PHYS_HISTORY = 'GET_PHYS_HISTORY'
export const GET_PHYS_HISTORY_SUCCESS = 'GET_PHYS_HISTORY_SUCCESS'
export const GET_PHYS_HISTORY_FAILED = 'GET_PHYS_HISTORY_FAILED'

export const GET_ENTITY_HISTORY = 'GET_ENTITY_HISTORY'
export const GET_ENTITY_HISTORY_SUCCESS = 'GET_ENTITY_HISTORY_SUCCESS'
export const GET_ENTITY_HISTORY_FAILED = 'GET_ENTITY_HISTORY_FAILED'