export const ADD_FAVORITE = 'ADD_FAVORITE'
export const ADD_FAVORITE_SUCCESS = 'ADD_FAVORITE_SUCCESS'
export const ADD_FAVORITE_FAILED = 'ADD_FAVORITE_FAILED'
export const ADD_FAVORITE_RESET = 'ADD_FAVORITE_RESET'

export const GET_FAVORITES = 'GET_FAVORITES'
export const GET_FAVORITES_SUCCESS = 'GET_FAVORITES_SUCCESS'
export const GET_FAVORITES_FAILED = 'GET_FAVORITES_FAILED'
export const GET_FAVORITES_RESET = 'GET_FAVORITES_RESET'

export const REMOVE_FAVORITE = 'REMOVE_FAVORITE'
export const REMOVE_FAVORITE_SUCCESS = 'REMOVE_FAVORITE_SUCCESS'
export const REMOVE_FAVORITE_FAILED = 'REMOVE_FAVORITE_FAILED'
export const REMOVE_FAVORITE_RESET = 'REMOVE_FAVORITE_RESET'